config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :gift_cards
  end
end

app/models/concerns/spree/order/gift_card.rb
module Spree
  class Order
    module GiftCard
      extend ActiveSupport::Concern

      def add_gift_card_payments(gift_card)
        payments.gift_cards.checkout.map(&:invalidate!)
        return unless gift_card.present?
        payment_method = Spree::PaymentMethod::GiftCard.available.first
        raise 'Gift Card payment method could not be found' unless payment_method
        amount_to_take = gift_card_amount(gift_card, outstanding_balance_after_applied_store_credit)
        create_gift_card_payment(payment_method, gift_card, amount_to_take)
      end

      def total_applied_gift_card
        payments.gift_cards.valid.sum(:amount)
      end

      def using_gift_card?
        total_applied_gift_card > 0
      end

      def display_total_applied_gift_card
        Spree::Money.new(-total_applied_gift_card, currency: currency)
      end

      included do
        def order_total_after_store_credit_with_gift_card
          order_total_after_store_credit_without_gift_card - total_applied_gift_card
        end
        alias_method :order_total_after_store_credit_without_gift_card, :order_total_after_store_credit
        alias_method :order_total_after_store_credit, :order_total_after_store_credit_with_gift_card
      end

      def add_store_credit_payments
        payments.store_credits.where(state: 'checkout').map(&:invalidate!)
        remaining_total = outstanding_balance - total_applied_gift_card
        return unless user && user.store_credits.any?
        payment_method = Spree::PaymentMethod::StoreCredit.available.first
        raise 'Store credit payment method could not be found' unless payment_method
        user.store_credits.order_by_priority.each do |credit|
          break if remaining_total.zero?
          next if credit.amount_remaining.zero?
          amount_to_take = store_credit_amount(credit, remaining_total)
          create_store_credit_payment(payment_method, credit, amount_to_take)
          remaining_total -= amount_to_take
        end
      end
      
      private

      def create_gift_card_payment(payment_method, gift_card, amount)
        payments.create!(
          source: gift_card,
          payment_method: payment_method,
          amount: amount,
          state: 'checkout',
          response_code: gift_card.generate_authorization_code
        )
      end

      def gift_card_amount(gift_card, total)
        [gift_card.amount_remaining, total].min
      end

      def outstanding_balance_after_applied_store_credit
        outstanding_balance - total_applied_store_credit
      end
    end
  end
end

app/models/spree/gift_card.rb
module Spree
  class GiftCard < ActiveRecord::Base
    include CalculatedAdjustments
    include Spree::GiftCard::Users

    UNACTIVATABLE_ORDER_STATES = %w[complete awaiting_return returned].freeze
    AUTHORIZE_ACTION = 'authorize'.freeze
    CAPTURE_ACTION = 'capture'.freeze
    VOID_ACTION = 'void'.freeze
    CREDIT_ACTION = 'credit'.freeze
    VALUES = [10, 25, 50, 100, 150, 200, 250, 300, 500, 1000].freeze

    before_validation :generate_code, on: :create
    before_validation :set_values, on: :create

    belongs_to :variant
    belongs_to :line_item, optional: true

    has_many :transactions, class_name: 'Spree::GiftCardTransaction'

    validates :current_value, :code, presence: true

    with_options allow_blank: true do
      validates :code, uniqueness: { case_sensitive: false }
      validates :current_value, numericality: { greater_than_or_equal_to: 0 }
      validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    end

    validates :email, :name, :sender_name, :sender_email, :note, presence: true
    validates :sender_email, format: { with: URI::MailTo::EMAIL_REGEXP }

    validate :amount_remaining_is_positive, if: :current_value

    scope :active, -> { where(active: true) }
    scope :inactive, -> { where(active: false) }

    def safely_redeem(user)
      if able_to_redeem?(user)
        redeem(user)
      elsif amount_remaining.to_f > 0.0
        errors[:base] = Spree.t('errors.gift_card.unauthorized')
        false
      else
        errors[:base] = Spree.t('errors.gift_card.already_redeemed')
        false
      end
    end

    def amount_remaining
      current_value - authorized_amount
    end

    def authorize(amount, options = {})
      authorization_code = options[:action_authorization_code]
      if authorization_code
        return true if transactions.find_by(action: AUTHORIZE_ACTION, authorization_code: authorization_code)
        errors.add(:base, Spree.t('gift_card_payment_method.unable_to_capture', auth_code: authorization_code))
        return false
      else
        authorization_code = generate_authorization_code
      end

      if valid_authorization?(amount)
        transaction = transactions.build(action: AUTHORIZE_ACTION, amount: amount, authorization_code: authorization_code)
        transaction.order = Spree::Order.find_by(number: options[:order_number]) if options[:order_number]
        self.authorized_amount = authorized_amount + amount
        save!
        authorization_code
      else
        false
      end
    end

    def valid_authorization?(amount)
      if amount_remaining.to_d < amount.to_d
        errors.add(:base, Spree.t('gift_card_payment_method.insufficient_funds'))
        false
      else
        true
      end
    end

    def capture(amount, authorization_code, options = {})
      return false unless authorize(amount, action_authorization_code: authorization_code)
      if amount <= authorized_amount
        transaction = transactions.build(action: CAPTURE_ACTION, amount: amount, authorization_code: authorization_code)
        transaction.order = Spree::Order.find_by(number: options[:order_number]) if options[:order_number]
        self.authorized_amount = authorized_amount - amount
        self.current_value = current_value - amount
        save!
        authorization_code
      else
        errors.add(:base, Spree.t('gift_card_payment_method.insufficient_authorized_amount'))
        false
      end
    end

    def void(authorization_code, options = {})
      auth_transaction = transactions.find_by(action: AUTHORIZE_ACTION, authorization_code: authorization_code)
      if auth_transaction
        amount = auth_transaction.amount
        transaction = transactions.build(action: VOID_ACTION, amount: amount, authorization_code: authorization_code)
        transaction.order = Spree::Order.find_by(number: options[:order_number]) if options[:order_number]
        self.authorized_amount = authorized_amount - amount
        save!
        true
      else
        errors.add(:base, Spree.t('gift_card_payment_method.unable_to_void', auth_code: authorization_code))
        false
      end
    end

    def credit(amount, authorization_code, options = {})
      capture_transaction = transactions.find_by(action: CAPTURE_ACTION, authorization_code: authorization_code)
      if capture_transaction && amount <= capture_transaction.amount
        transaction = transactions.build(action: CREDIT_ACTION, amount: amount, authorization_code: authorization_code)
        transaction.order = Spree::Order.find_by(number: options[:order_number]) if options[:order_number]
        self.current_value = current_value + amount
        save!
        true
      else
        errors.add(:base, Spree.t('gift_card_payment_method.unable_to_credit', auth_code: authorization_code))
        false
      end
    end

    # Calculate the amount to be used when creating an adjustment
    def compute_amount(calculable)
      calculator.compute(calculable, self)
    end

    def debit(amount, order = nil)
      raise 'Cannot debit gift card by amount greater than current value.' if (amount_remaining - amount.to_f.abs) < 0
      transaction = transactions.build
      transaction.amount = amount
      transaction.order  = order if order
      self.current_value = current_value - amount.abs
      save
    end

    def price
      line_item ? line_item.price * line_item.quantity : variant.price
    end

    def order_activatable?(order)
      order &&
        created_at < order.created_at &&
        current_value > 0 &&
        !UNACTIVATABLE_ORDER_STATES.include?(order.state)
    end

    def calculator
      @calculator ||= Spree::Calculator::GiftCardCalculator.new
    end

    def actions
      %i[capture void]
    end

    def generate_authorization_code
      "#{id}-GC-#{Time.now.utc.strftime('%Y%m%d%H%M%S%6N')}"
    end

    def can_void?(payment)
      payment.pending?
    end

    def can_capture?(payment)
      %w[checkout pending].include?(payment.state)
    end

    private

    def redeem(user)
      transaction do
        previous_current_value = amount_remaining
        debit(amount_remaining)
        build_store_credit(user, previous_current_value).save!
      end
    rescue StandardError
      errors[:base] = 'There some issue while redeeming the gift card.'
      false
    end

    def build_store_credit(user, previous_current_value)
      user.store_credits.build(
        amount: previous_current_value,
        category: Spree::StoreCreditCategory.gift_card.last,
        memo: "Gift Card - #{line_item.product.name} received from #{recieved_from}",
        created_by: user,
        action_originator: user,
        currency: Spree::Config[:currency]
      )
    end

    def recieved_from
      line_item.order.email
    end

    # TODO find if some generator can create unique code
    def generate_code
      until code.present? && self.class.where(code: code).count.zero?
        chars = [('A'..'Z'), ('0'..'9')].map(&:to_a).flatten
        self.code = Array.new(8) { chars[rand(chars.count)] }.join
      end
    end

    def set_values
      self.current_value ||= line_item.try(:price)
    end

    def amount_remaining_is_positive
      unless amount_remaining >= 0.0
        errors.add(:authorized_amount, Spree.t('errors.gift_card.greater_than_current_value'))
      end
    end

    def able_to_redeem?(user)
      Spree::Config.allow_gift_card_redeem &&
        user &&
        user.email == email &&
        amount_remaining.to_f > 0.0 && line_item.order.completed?
    end
  end
end

app/models/spree/gift_card/users.rb
module Spree
  # GiftCard class enhancement
  class GiftCard < ActiveRecord::Base
    has_many :user_gift_cards
    has_many :users, through: :user_gift_cards

    # GiftCard may have many owners
    module Users
      def belongs_to?(user)
        owners.include?(user)
      end
    end
  end
end

app/controllers/spree/admin/gift_cards_controller.rb
module Spree
  module Admin
    class GiftCardsController < ResourceController
      before_action :find_gift_card_variants, only: [:new, :edit]

      def create
        begin
          # Wrap the transaction script in a transaction so it is an atomic operation
          Spree::GiftCard.transaction do
            @gift_card = GiftCard.new(gift_card_params)
            @gift_card.current_value = @gift_card.variant.price
            @gift_card.save!

            # Create line item
            line_item = LineItem.new(quantity: 1)
            line_item.gift_card = @gift_card
            line_item.variant = @gift_card.variant
            line_item.price = @gift_card.variant.price

            # Add to order
            @order = Spree::Order.new(
              created_by_id: try_spree_current_user.try(:id),
              store_id: Spree::Store.current,
            )
            @order.line_items << line_item
            line_item.order = @order
            @order.update_totals
            @order.updater.update_item_count
            @order.save!

            # Save gift card
            @gift_card.line_item = line_item
            @gift_card.save!
          end

          redirect_to spree.edit_admin_order_url(@order)
        rescue ActiveRecord::RecordInvalid
          find_gift_card_variants
          render :new
        end
      end

      def update
        begin
          Spree::GiftCard.transaction do
            @gift_card.assign_attributes(gift_card_params)
           
            if @gift_card.variant_id_changed?
              @gift_card.current_value = @gift_card.variant.price

              @gift_card.line_item.update!(
                variant: @gift_card.variant,
                price: @gift_card.variant.price
              )
  
              @order = @gift_card.line_item.order

              # TODO is not updating adjustment properly i think
              
              @order.update_totals
              @order.updater.update_item_count
              @order.save!
            end

            @gift_card.save!
          end

          redirect_to spree.edit_admin_gift_card_url(@gift_card)
        rescue ActiveRecord::RecordInvalid
          find_gift_card_variants
          render :edit
        end
      end

      def destroy
        begin
          Spree::GiftCard.transaction do
            @order = @gift_card.line_item.order
            
            @gift_card.line_item.destroy

            @order.update_totals
            @order.updater.update_item_count
            @order.save!

            invoke_callbacks(:destroy, :before)
            if @gift_card.destroy
              invoke_callbacks(:destroy, :after)
              flash[:success] = flash_message_for(@gift_card, :successfully_removed)
            else
              invoke_callbacks(:destroy, :fails)
              flash[:error] = @gift_card.errors.full_messages.join(', ')
            end

            respond_with(@gift_card) do |format|
              format.html { redirect_to location_after_destroy }
              format.js   { render_js_for_destroy }
            end
          end
        rescue ActiveRecord::RecordInvalid
          # TODO
        end
      end
      
      private

      def collection
        return @collection if @collection.present?

        params[:q] ||= {}
        @collection = super.order(created_at: :desc)

        @search = @collection.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(params[:per_page])
      end

      def find_gift_card_variants
        @gift_card_product = Product.not_deleted.gift_cards.first
        
        @gift_card_variants = @gift_card_product.variants
                                                .joins(:prices)
                                                .where("amount > 0")
                                                .order("amount")
      end
  
      def gift_card_params
        params.require(:gift_card).permit(:email, :name, :note, :variant_id, :sender_name)
      end
    end
  end
end

app/helpers/spree/admin/gift_cards_helper.rb
module Spree::Admin::GiftCardsHelper
  def variants_values(gift_card_variants)
    gift_card_variants.map { |variant| ["#{variant.display_price} - #{variant.product.name}", variant.id] }
  end
end

app/helpers/spree/gift_cards_helper.rb
module Spree::GiftCardsHelper
  def variants_values(gift_card_variants)
    gift_card_variants.map { |variant| ["#{variant.display_price} - #{variant.product.name}", variant.id] }
  end
end

app/views/spree/admin/gift_cards/_form.html.erb
<div data-hook="admin_gift_card_form_fields">
  <%= f.field_container :variant, class: ['form-group'], 'data-hook' => 'email' do %>
    <%= f.label :variant_id, Spree.t(:value) %>
    <%= f.select :variant_id, variants_values(@gift_card_variants), { selected: @gift_card.variant_id }, class: 'select2' %>
    <%= f.error_message_on :variant_id %>
  <% end %>

  <%= f.field_container :email, class: ['form-group'], 'data-hook' => 'email' do %>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
    <%= f.error_message_on :email %>
  <% end %>

  <%= f.field_container :name, class: ['form-group'], 'data-hook' => 'name' do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.error_message_on :name %>
  <% end %>

  <%= f.field_container :sender_name, class: ['form-group'], 'data-hook' => 'sender_name' do %>
    <%= f.label :sender_name %>
    <%= f.text_field :sender_name, class: 'form-control' %>
    <%= f.error_message_on :sender_name %>
  <% end %>

  <%= f.field_container :note, class: ['form-group'], 'data-hook' => 'note' do %>
    <%= f.label :note %>
    <%= f.text_area :note, rows: 3, class: 'form-control' %>
    <%= f.error_message_on :note %>
  <% end %>
</div>

app/views/spree/admin/gift_cards/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:gift_cards), spree.admin_gift_cards_path %> /
  <%= Spree.t(:editing_gift_card) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:back_to_gift_cards_list), spree.admin_gift_cards_path, icon: 'icon-arrow-left' %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @gift_card } %>

<%= form_for [:admin, @gift_card] do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= render partial: 'spree/admin/shared/edit_resource_links' %>
<% end %>

<h2><%= Spree.t(:transactions) %><h2>
<ul>
  <% @gift_card.transactions.each do |transaction| %>
  <li><%= link_to("#{transaction.order.number}:" , edit_admin_order_path(transaction.order)) if transaction.order.present? %> <%= number_to_currency transaction.amount %></li>
  <% end %>
</ul>

app/views/spree/admin/gift_cards/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:gift_cards) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_gift_card), new_admin_gift_card_url, { class: "btn-success", icon: 'add.svg', id: 'new_gift_card' } %>
<% end %>

<% if @collection.any? %>
<div class="table-responsive">
  <table class="table" id="listing_gift_cards">
    <thead>
      <tr data-hook="admin_gift_cards_index_headers">
        <th scope="col"><%= Spree.t(:code) %></th>
        <th scope="col"><%= Spree.t(:current_value) %></th>
        <th scope="col"><%= Spree.t(:email) %></th>
        <th scope="col"><%= Spree.t(:name) %></th>
        <th scope="col"><%= Spree.t(:sender_name) %></th>
        <th scope="col" data-hook="admin_gift_cards_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |card| %>
        <tr id="<%= spree_dom_id card %>">
          <td><%= card.code %></td>
          <td><%= number_to_currency card.current_value %></td>
          <td><%= card.email %></td>
          <td><%= card.name %></td>
          <td><%= card.sender_name %></td>
          <td class="actions" data-hook="admin_gift_cards_index_row_actions">
            <span class="d-flex justify-content-end">
              <%= link_to_edit card, no_text: true, class: 'edit' if can?(:edit, card) %>
              <%= link_to_delete card, no_text: true if can?(:delete, card) %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree.t('gift_cards')) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/admin/gift_cards/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:gift_cards), spree.admin_gift_cards_path %> /
  <%= Spree.t(:new_gift_card) %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @gift_card } %>

<%= form_for @gift_card, url: collection_url do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>